# Generated by Django 6.0.6 on 2026-06-27 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(blank=True, max_length=20, null=True)),
                ('meal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('donation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cashier', models.ForeignKey(blank=True, db_column='cashier_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.cafeteriacashier')),
                ('customer', models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.cafeteriacustomer')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
