# Generated by Django 6.0.6 on 2026-06-27 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionBatch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('distribution_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('beneficiary_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'distribution_batch',
            },
        ),
        migrations.CreateModel(
            name='DonationPool',
            fields=[
                ('pool_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_distribution_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'donation_pool',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('donation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('donation_type', models.CharField(blank=True, max_length=30, null=True)),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='accounts.cafeteriacustomer')),
                ('payment', models.ForeignKey(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='payments.payment')),
            ],
            options={
                'db_table': 'donation',
            },
        ),
    ]
