# Generated by Django 6.0.6 on 2026-06-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('annual_target', models.DecimalField(decimal_places=2, default=100000.0, max_digits=12)),
            ],
            options={
                'db_table': 'donation_goal',
            },
        ),
    ]
