# Generated by Django 6.0.6 on 2026-06-27 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('beneficiary_id', models.AutoField(primary_key=True, serialize=False)),
                ('learner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tap2eat_acc_no', models.CharField(blank=True, max_length=50, null=True)),
                ('eligibility_score', models.IntegerField(blank=True, null=True)),
                ('allocation_status', models.CharField(blank=True, max_length=20, null=True)),
                ('support_cycle_count', models.IntegerField(default=0)),
                ('reassessment_status', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('representative', models.ForeignKey(blank=True, db_column='representative_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='accounts.schoolrepresentative')),
            ],
            options={
                'db_table': 'beneficiary',
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('allocation_id', models.AutoField(primary_key=True, serialize=False)),
                ('allocation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('allocation_date', models.DateTimeField(auto_now_add=True)),
                ('priority_level', models.CharField(blank=True, max_length=20, null=True)),
                ('batch', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='donations.distributionbatch')),
                ('beneficiary', models.ForeignKey(db_column='beneficiary_id', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='beneficiaries.beneficiary')),
            ],
            options={
                'db_table': 'allocation',
            },
        ),
        migrations.CreateModel(
            name='EligibilityAssessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('questionnaire_score', models.IntegerField(blank=True, null=True)),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(db_column='beneficiary_id', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='beneficiaries.beneficiary')),
            ],
            options={
                'db_table': 'eligibility_assessment',
            },
        ),
    ]
