# Generated by Django 6.0.6 on 2026-06-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='last_allocation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eligibilityassessment',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='eligibilityassessment',
            name='evidence_statement_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eligibilityassessment',
            name='evidence_statement_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eligibilityassessment',
            name='inconsistency_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eligibilityassessment',
            name='inconsistency_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eligibilityassessment',
            name='is_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eligibilityassessment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='eligibilityassessment',
            name='total_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eligibilityassessment',
            name='verification_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='allocation_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending_approval', 'Pending Approval'), ('not_eligible', 'Not Eligible'), ('flagged', 'Flagged for Reassessment')], default='pending_approval', max_length=32),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='reassessment_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending_reassessment', 'Pending Reassessment'), ('flagged', 'Flagged')], default='not_required', max_length=32),
        ),
    ]
