# Generated by Django 6.0.6 on 2026-06-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_beneficiary_last_allocation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='learner_gender',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
