# Generated by Django 6.0.6 on 2026-06-30 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0003_beneficiary_learner_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='reassessment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='removal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='removal_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ReassessmentRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('evidence_statement_1', models.TextField(blank=True)),
                ('evidence_statement_2', models.TextField(blank=True)),
                ('verification_confirmed', models.BooleanField(default=False)),
                ('total_score', models.IntegerField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('remove', 'Remove from programme'), ('under_review', 'Continue under review'), ('continue_support', 'Continue support'), ('high_priority', 'High-priority beneficiary')], max_length=32)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(db_column='beneficiary_id', on_delete=django.db.models.deletion.CASCADE, related_name='reassessments', to='beneficiaries.beneficiary')),
            ],
            options={
                'db_table': 'beneficiary_reassessment',
            },
        ),
    ]
