# Generated by Django 6.0.6 on 2026-06-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0004_beneficiary_is_removed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='pending_half_cycle',
            field=models.BooleanField(default=False),
        ),
    ]
