# Generated by Django 6.0.6 on 2026-06-26 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeteriaCashier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id_number', models.CharField(max_length=120)),
                ('employee_number', models.CharField(max_length=120)),
                ('workstation_number', models.CharField(max_length=120)),
                ('institution_name', models.CharField(max_length=255)),
                ('years_of_service', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cafeteria_cashier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cafeteria_cashier',
            },
        ),
        migrations.CreateModel(
            name='CafeteriaCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cafeteria_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cafeteria_customer',
            },
        ),
        migrations.CreateModel(
            name='RoleUpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(choices=[('school_representative', 'School Representative'), ('cashier', 'Cashier')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('school_name', models.CharField(blank=True, max_length=255)),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('institution_details', models.TextField(blank=True)),
                ('verification_info', models.TextField(blank=True)),
                ('cashier_id', models.CharField(blank=True, max_length=120)),
                ('national_id', models.CharField(blank=True, max_length=120)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_role_upgrade_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_upgrade_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('school_code', models.CharField(max_length=120, unique=True)),
                ('tsc_number', models.CharField(max_length=120)),
                ('national_id_number', models.CharField(max_length=120)),
                ('position', models.CharField(max_length=120)),
                ('years_of_service', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_representative', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'school_representative',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer_donor', 'Cafeteria Customer (Donor)'), ('cashier', 'Cafeteria Cashier'), ('school_representative', 'School Representative'), ('system_admin', 'System Administrator')], default='customer_donor', max_length=32)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('account_status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending')], default='Active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_user',
            },
        ),
    ]
