# Generated by Django 6.0.6 on 2026-06-26 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafeteriacashier',
            name='years_of_service',
        ),
    ]
