# Generated by Django 6.0.6 on 2026-06-27 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(default='CAFETERIA_CUSTOMER', max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('account_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_user',
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_logs', to='accounts.systemuser')),
            ],
            options={
                'db_table': 'system_logs',
            },
        ),
        migrations.CreateModel(
            name='SystemAdministrator',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('access_level', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='system_administrator', to='accounts.systemuser')),
            ],
            options={
                'db_table': 'system_administrator',
            },
        ),
        migrations.CreateModel(
            name='SchoolRepresentative',
            fields=[
                ('representative_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(blank=True, max_length=100, null=True)),
                ('school_code', models.IntegerField(blank=True, null=True, unique=True)),
                ('tsc_number', models.CharField(blank=True, max_length=30, null=True)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('years_of_service', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='school_representative', to='accounts.systemuser')),
            ],
            options={
                'db_table': 'school_representative',
            },
        ),
        migrations.CreateModel(
            name='CafeteriaCustomer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('donor_status', models.CharField(blank=True, max_length=20, null=True)),
                ('total_donations', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='cafeteria_customer', to='accounts.systemuser')),
            ],
            options={
                'db_table': 'cafeteria_customer',
            },
        ),
        migrations.CreateModel(
            name='CafeteriaCashier',
            fields=[
                ('cashier_id', models.AutoField(primary_key=True, serialize=False)),
                ('workstation_number', models.CharField(blank=True, max_length=20, null=True)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('employee_number', models.CharField(blank=True, max_length=30, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=100, null=True)),
                ('years_of_service', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='cafeteria_cashier', to='accounts.systemuser')),
            ],
            options={
                'db_table': 'cafeteria_cashier',
            },
        ),
    ]
