# Generated by Django 6.0.6 on 2026-06-27 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=32, unique=True)),
                ('role', models.CharField(choices=[('customer_donor', 'Cafeteria Customer (Donor)'), ('cashier', 'Cafeteria Cashier'), ('school_representative', 'School Representative'), ('system_admin', 'System Administrator')], default='customer_donor', max_length=32)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_user_profile',
            },
        ),
    ]
