# Generated by Django 6.0.6 on 2026-06-30 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appuserprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolrepresentative',
            name='national_id',
        ),
        migrations.AddField(
            model_name='schoolrepresentative',
            name='national_id_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='schoolrepresentative',
            name='position',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='schoolrepresentative',
            name='school_code',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolrepresentative',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schoolrepresentative',
            name='tsc_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='schoolrepresentative',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_representative', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schoolrepresentative',
            name='years_of_service',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
