# Generated by ChatGPT on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_schoolrepresentative_national_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuserprofile",
            name="can_initiate_cycles",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appuserprofile",
            name="can_manage_beneficiaries",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="appuserprofile",
            name="can_manage_users",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appuserprofile",
            name="can_view_reports",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="appuserprofile",
            name="status_note",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
