# Generated by Django 6.0.6 on 2026-06-27 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(blank=True, max_length=50, null=True)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('report_status', models.CharField(blank=True, max_length=20, null=True)),
                ('admin', models.ForeignKey(blank=True, db_column='admin_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.systemadministrator')),
            ],
            options={
                'db_table': 'report',
            },
        ),
    ]
