# Generated by ChatGPT on 2026-06-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AllocationLogicConfig",
            fields=[
                ("config_id", models.AutoField(primary_key=True, serialize=False)),
                ("full_cycle_per_learner", models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ("half_cycle_per_learner", models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allocation_logic_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "allocation_logic_config"},
        ),
    ]
