# Generated by ChatGPT on 2026-07-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UrgentSupportMessage",
            fields=[
                ("message_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sender_role",
                    models.CharField(
                        choices=[
                            ("school_representative", "School Representative"),
                            ("cashier", "Cafeteria Cashier"),
                        ],
                        max_length=32,
                    ),
                ),
                ("message_text", models.TextField()),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="urgent_messages_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urgent_messages_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "urgent_support_message"},
        ),
    ]
